test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -147,6 +147,7 @@ jobs:
                 echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
                 echo -e "${warnings[$extension]}" >> ./report.md
             done
+            exit 1  # Exiting with code 1 for FAILED status
         elif [ $total_errors -eq 0 ] && [ $total_warnings -gt 0 ]; then
             echo "Status: \`WARNING\`" >> ./report.md
             echo -e "\nSome assets exceed the specified limit in the following directories: \`$asset_paths\`, but they do not fail the validation because they are ignored by configuration." >> ./report.md
@@ -169,6 +170,7 @@ jobs:
                 echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
                 echo -e "${errors[$extension]}" >> ./report.md
             done
+            exit 1  # Exiting with code 1 for FAILED status
         else
             echo "Status: \`SUCCESS\`" >> ./report.md
             echo -e "\nAll assets match the size limit for their file types in the following directories: \`$asset_paths\`." >> ./report.md
