feature(getpin-3681): test

diff --git a/.github/workflows/blank2.yml b/.github/workflows/blank2.yml
--- a/.github/workflows/blank2.yml
+++ b/.github/workflows/blank2.yml
@@ -1,17 +1,32 @@
-name: Get Last Commit Name
+name: Check commit
 
 on:
   workflow_call:
 
 jobs:
-  get-last-commit-name:
+  check_commit:
     runs-on: ubuntu-latest
-    outputs:
-      commit-name: ${{ steps.display.outputs.commit-name }}
+
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Get last commit name
-      id: display
-      run: echo "::set-output name=commit-name::$(git log -1 --pretty=format:'%s')"
+      uses: actions/checkout@v4
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+    
+    - name: check commit
+      run: |
+        last_commit_message=$(git log --format="%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
+        if ! echo "$last_commit_message" | grep -qE "(fix|hotfix|bugfix|feat|feature|breaking)((.+))?:.+"; then
+          echo "::set-output name=validation_result::invalid"
+        else
+          echo "::set-output name=validation_result::valid"
+        fi
+        git show -s --format="%s"
+        echo "$last_commit_message"
+    
+    # - name: Post comment on Pull Request
+    #   if: ${{ always() }}
+    #   uses: thollander/actions-comment-pull-request@v2
+    #   with:
+    #     message: |
+    #       ${{ steps.validate.outputs.validation_result }} There are valid commits according to regulation.
