dev

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -38,58 +38,58 @@ jobs:
 
         # Parse input parameters for asset types and their limits
         parse_input_params() {
-            local input_types="$1"
-            local type_limit_pair
-            for type_limit_pair in $input_types; do
-                local type=$(echo "$type_limit_pair" | cut -d':' -f1)
-                local limit_with_unit=$(echo "$type_limit_pair" | cut -d':' -f2)
-                local numeric_limit=$(echo "$limit_with_unit" | sed 's/[^0-9.]//g')
-                local unit=$(echo "$limit_with_unit" | sed 's/[0-9.]//g')
+          local input_types="$1"
+          local type_limit_pair
+          for type_limit_pair in $input_types; do
+            local type=$(echo "$type_limit_pair" | cut -d':' -f1)
+            local limit_with_unit=$(echo "$type_limit_pair" | cut -d':' -f2)
+            local numeric_limit=$(echo "$limit_with_unit" | sed 's/[^0-9.]//g')
+            local unit=$(echo "$limit_with_unit" | sed 's/[0-9.]//g')
                 
-                case $unit in
-                    "GB") limit=$(python -c "print(int($numeric_limit * 1024 * 1024 * 1024))");;
-                    "MB") limit=$(python -c "print(int($numeric_limit * 1024 * 1024))");;
-                    "KB") limit=$(python -c "print(int($numeric_limit * 1024))");;
-                    *) limit=$numeric_limit;;
-                esac
+            case $unit in
+              "GB") limit=$(python -c "print(int($numeric_limit * 1024 * 1024 * 1024))");;
+              "MB") limit=$(python -c "print(int($numeric_limit * 1024 * 1024))");;
+              "KB") limit=$(python -c "print(int($numeric_limit * 1024))");;
+              *) limit=$numeric_limit;;
+            esac
                 
-                limits["$type"]="$limit"
-            done
+            limits["$type"]="$limit"
+          done
         }
 
         convert() {
-            local bytes=$1
-            if (( bytes < 1024 )); then
-                echo "${bytes} bytes"
-            elif (( bytes < 1048576 )); then
-                echo "$(( bytes / 1024 )) KB"
-            elif (( bytes < 1073741824 )); then
-                printf "%.2f MB" "$(echo "scale=2; $bytes / 1024 / 1024" | bc)"
-            else
-                printf "%.2f GiB" "$(echo "scale=2; $bytes / 1024 / 1024 / 1024" | bc)"
-            fi
+          local bytes=$1
+          if (( bytes < 1024 )); then
+            echo "${bytes} bytes"
+          elif (( bytes < 1048576 )); then
+            echo "$(( bytes / 1024 )) KB"
+          elif (( bytes < 1073741824 )); then
+            printf "%.2f MB" "$(echo "scale=2; $bytes / 1024 / 1024" | bc)"
+          else
+            printf "%.2f GiB" "$(echo "scale=2; $bytes / 1024 / 1024 / 1024" | bc)"
+          fi
         }
 
         check_file_size() {
-            local file="$1"
-            local size=$(stat -c %s "$file")
-            local extension="${file##*.}"
-            local extension="${extension,,}"
-            local limit="${limits[$extension]}"
+          local file="$1"
+          local size=$(stat -c %s "$file")
+          local extension="${file##*.}"
+          local extension="${extension,,}"
+          local limit="${limits[$extension]}"
             
-            if [ -n "$limit" ]; then
-                if [ "$size" -gt "$limit" ]; then
-                    if [[ " ${IGNORED_ASSETS[*]} " =~ "$file" ]]; then
-                        echo -e "::warning::File $file exceeds the limit for type .$extension \e[31mSize\e[0m: $(convert $size) (\e[32mLimit\e[0m: $(convert $limit))"
-                        warnings["$extension"]+="- \`$file\` Size: <b>$(convert $size)</b>\n"
-                        total_warnings=$((total_warnings + 1))
-                    else
-                        echo -e "::error::File $file exceeds the limit for type .$extension \e[31mSize\e[0m: $(convert $size) (\e[32mLimit\e[0m: $(convert $limit))"
-                        errors["$extension"]+="- \`$file\` Size: <b>$(convert $size)</b>\n"
-                        total_errors=$((total_errors + 1))
-                    fi
-                fi
+          if [ -n "$limit" ]; then
+            if [ "$size" -gt "$limit" ]; then
+              if [[ " ${IGNORED_ASSETS[*]} " =~ "$file" ]]; then
+                echo -e "::warning::File $file exceeds the limit for type .$extension \e[31mSize\e[0m: $(convert $size) (\e[32mLimit\e[0m: $(convert $limit))"
+                warnings["$extension"]+="- \`$file\` Size: <b>$(convert $size)</b>\n"
+                total_warnings=$((total_warnings + 1))
+              else
+                echo -e "::error::File $file exceeds the limit for type .$extension \e[31mSize\e[0m: $(convert $size) (\e[32mLimit\e[0m: $(convert $limit))"
+                errors["$extension"]+="- \`$file\` Size: <b>$(convert $size)</b>\n"
+                total_errors=$((total_errors + 1))
+              fi
             fi
+          fi
         }
 
         # Main script starts here
@@ -104,74 +104,74 @@ jobs:
         total_warnings=0
 
         recursive_check() {
-            local current_path="$1"
-            if [ -d "$current_path" ]; then
-                for item in "$current_path"/*; do
-                    if [ -f "$item" ]; then
-                        check_file_size "$item"
-                    elif [ -d "$item" ]; then
-                        recursive_check "$item"
-                    fi
-                done
-            else
-                check_file_size "$current_path"
-            fi
+          local current_path="$1"
+          if [ -d "$current_path" ]; then
+            for item in "$current_path"/*; do
+              if [ -f "$item" ]; then
+                check_file_size "$item"
+              elif [ -d "$item" ]; then
+                recursive_check "$item"
+              fi
+            done
+          else
+            check_file_size "$current_path"
+          fi
         }
 
         for path in "${ASSET_PATHS[@]}"; do
-            recursive_check "$path"
+          recursive_check "$path"
         done
 
         # Print report
         echo "# Assets Size Validation Report" > ./report.md
 
         if [ $total_errors -gt 0 ] && [ $total_warnings -gt 0 ]; then
-            echo "Status: \`FAILED\`" >> ./report.md
-            echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`" >> ./report.md
-            echo -e "\nTotal Errors: <b>$total_errors</b>" >> ./report.md
-            echo -e "Total Warnings: <b>$total_warnings</b>" >> ./report.md
-            echo -e "\n## Errors" >> ./report.md
+          echo "Status: \`FAILED\`" >> ./report.md
+          echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`" >> ./report.md
+          echo -e "\nTotal Errors: <b>$total_errors</b>" >> ./report.md
+          echo -e "Total Warnings: <b>$total_warnings</b>" >> ./report.md
+          echo -e "\n## Errors" >> ./report.md
 
-            for extension in "${!errors[@]}"; do
-                echo -e "<b>$extension</b>" >> ./report.md
-                echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
-                echo -e "${errors[$extension]}" >> ./report.md
-            done
+          for extension in "${!errors[@]}"; do
+            echo -e "<b>$extension</b>" >> ./report.md
+            echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
+            echo -e "${errors[$extension]}" >> ./report.md
+          done
 
-            echo -e "\n## Warnings" >> ./report.md
+          echo -e "\n## Warnings" >> ./report.md
 
-            for extension in "${!warnings[@]}"; do
-                echo -e "<b>$extension</b>" >> ./report.md
-                echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
-                echo -e "${warnings[$extension]}" >> ./report.md
-            done
-            exit 1  # Exiting with code 1 for FAILED status
+          for extension in "${!warnings[@]}"; do
+            echo -e "<b>$extension</b>" >> ./report.md
+            echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
+            echo -e "${warnings[$extension]}" >> ./report.md
+          done
+          exit 1  # Exiting with code 1 for FAILED status
         elif [ $total_errors -eq 0 ] && [ $total_warnings -gt 0 ]; then
-            echo "Status: \`WARNING\`" >> ./report.md
-            echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`, but they do not fail the validation because they are ignored by configuration." >> ./report.md
-            echo -e "\nTotal Warnings: <b>$total_warnings</b>" >> ./report.md
-            echo -e "\n## Warnings" >> ./report.md
+          echo "Status: \`WARNING\`" >> ./report.md
+          echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`, but they do not fail the validation because they are ignored by configuration." >> ./report.md
+          echo -e "\nTotal Warnings: <b>$total_warnings</b>" >> ./report.md
+          echo -e "\n## Warnings" >> ./report.md
 
-            for extension in "${!warnings[@]}"; do
-                echo -e "<b>$extension</b>" >> ./report.md
-                echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
-                echo -e "${warnings[$extension]}" >> ./report.md
-            done
+          for extension in "${!warnings[@]}"; do
+            echo -e "<b>$extension</b>" >> ./report.md
+            echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
+            echo -e "${warnings[$extension]}" >> ./report.md
+          done
         elif [ $total_errors -gt 0 ] && [ $total_warnings -eq 0 ]; then
-            echo "Status: \`FAILED\`" >> ./report.md
-            echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`" >> ./report.md
-            echo -e "\nTotal Errors: <b>$total_errors</b>" >> ./report.md
-            echo -e "\n## Errors" >> ./report.md
+          echo "Status: \`FAILED\`" >> ./report.md
+          echo -e "\nSome assets exceed the specified limit in the following directories: \`${ASSET_PATHS[*]}\`" >> ./report.md
+          echo -e "\nTotal Errors: <b>$total_errors</b>" >> ./report.md
+          echo -e "\n## Errors" >> ./report.md
 
-            for extension in "${!errors[@]}"; do
-                echo -e "<b>$extension</b>" >> ./report.md
-                echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
-                echo -e "${errors[$extension]}" >> ./report.md
-            done
-            exit 1  # Exiting with code 1 for FAILED status
+          for extension in "${!errors[@]}"; do
+            echo -e "<b>$extension</b>" >> ./report.md
+            echo -e "Limit: <b>$(convert ${limits[$extension]})</b>" >> ./report.md
+            echo -e "${errors[$extension]}" >> ./report.md
+          done
+          exit 1  # Exiting with code 1 for FAILED status
         else
-            echo "Status: \`SUCCESS\`" >> ./report.md
-            echo -e "\nAll assets match the size limit for their file types in the following directories: \`${ASSET_PATHS[*]}\`." >> ./report.md
+          echo "Status: \`SUCCESS\`" >> ./report.md
+          echo -e "\nAll assets match the size limit for their file types in the following directories: \`${ASSET_PATHS[*]}\`." >> ./report.md
             echo -e "\nNo actions required." >> ./report.md
         fi
 
