Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -35,6 +35,14 @@ jobs:
       run: |
         OUTPUT=$(bash ./check.sh)
         echo "::set-output name=report::$OUTPUT"
+        if [[ $OUTPUT =~ "::error::" ]]; then
+          echo "${OUTPUT}"
+          exit 1
+        elif [[ $OUTPUT =~ "Warning" ]]; then
+          echo "${OUTPUT}"
+        else
+          echo "All assets match required size"
+        fi
 
     - name: Post report as comment
       if: ${{ always() }}
